ARG OS_IMAGE=centos
ARG OS_VERSION=8
ARG ANSIBLE_VERSION=2.9

FROM $OS_IMAGE:$OS_VERSION
ARG OS_VERSION
ARG ANSIBLE_VERSION

# hadolint ignore=DL3033
RUN yum install -y python3 python3-pip && yum clean all
RUN pip3 install --no-cache-dir "ansible==$ANSIBLE_VERSION"
