ARG OS_VERSION=21.04
ARG OS_IMAGE=ubuntu
ARG ANSIBLE_VERSION=2.9
ARG WORKDIR=/workdir

FROM $OS_IMAGE:$OS_VERSION
ARG ANSIBLE_VERSION
ARG WORKDIR
ARG OS_IMAGE
ARG OS_VERSION
ARG BUILD_DATE=unknown
ARG VCS_REF=unknown

LABEL os_image="$OS_IMAGE"
LABEL os_version="$OS_VERSION"
LABEL ansible_version="$ANSIBLE_VERSION"
LABEL maintainer="info@kdaweb.com"
LABEL name="Ansible test image"
LABEL description="A Docker image for Ansible v$ANSIBLE_VERSION $OS_IMAGE:$OS_VERSION"
LABEL url="https://kdaweb.com/"
LABEL vcs-ref="$VCS_REF"
LABEL build-date="$BUILD_DATE"
LABEL docker.cmd="docker run --rm -it -v "$(pwd):/workdir" kdaweb/ansible-$ANSIBLE_VERSION-tester-$OS_IMAGE:$OS_VERSION"

RUN [ ! -d "$WORKDIR" ] && mkdir -p "$WORKDIR"

WORKDIR $WORKDIR

# hadolint ignore=DL3008
RUN apt-get update \
  && apt-get install --no-install-recommends -fy \
    python3 \
    python3-pip \
    python3-dev \
    build-essential \
    libffi-dev \
    libssl-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir "ansible==$ANSIBLE_VERSION"

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
