ARG OS_IMAGE=centos
ARG OS_VERSION=7
ARG ANSIBLE_VERSION=2.9
ARG WORKDIR=/workdir

FROM $OS_IMAGE:$OS_VERSION
ARG OS_VERSION
ARG ANSIBLE_VERSION
ARG WORKDIR

LABEL os_image="$OS_IMAGE"
LABEL os_version="$OS_VERSION"
LABEL ansible_version="$ANSIBLE_VERSION"
LABEL maintainer="info@kdaweb.com"
LABEL name="Ansible test image"
LABEL description="A Docker image for Ansible v$ANSIBLE_VERSION $OS_IMAGE:$OS_VERSION"
LABEL url="https://kdaweb.com/"

RUN [ ! -d "$WORKDIR" ] && mkdir -p "$WORKDIR"

WORKDIR $WORKDIR

# hadolint ignore=DL3033
RUN yum install -y python3 python3-pip && yum clean all
RUN pip3 install --no-cache-dir "ansible==$ANSIBLE_VERSION"

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
