ARG OS_VERSION=3.12
ARG OS_IMAGE=alpine
ARG ANSIBLE_VERSION=2.9

FROM $OS_IMAGE:$OS_VERSION
ARG ANSIBLE_VERSION
ARG OS_VERSION

RUN echo "http://dl-cdn.alpinelinux.org/alpine/v$OS_VERSION/main" > /etc/apk/repositories && echo "http://dl-cdn.alpinelinux.org/alpine/v$OS_VERSION/community" >> /etc/apk/repositories && apk update

# hadolint ignore=DL3018
RUN apk add --no-cache gcc git libffi-dev musl-dev openssl-dev perl py-pip python3 python3-dev sshpass
RUN pip install --no-cache-dir  "ansible==$ANSIBLE_VERSION"
