ARG OS_VERSION=3.12
ARG OS_IMAGE=alpine
ARG ANSIBLE_VERSION=2.9
ARG WORKDIR=/workdir

FROM $OS_IMAGE:$OS_VERSION
ARG ANSIBLE_VERSION
ARG OS_VERSION
ARG OS_IMAGE
ARG WORKDIR
ARG VCS_REF
ARG BUILD_DATE

RUN [ ! -d "$WORKDIR" ] && mkdir -p "$WORKDIR"

WORKDIR $WORKDIR

RUN echo "http://dl-cdn.alpinelinux.org/alpine/v$OS_VERSION/main" > /etc/apk/repositories && echo "http://dl-cdn.alpinelinux.org/alpine/v$OS_VERSION/community" >> /etc/apk/repositories && apk update

# hadolint ignore=DL3018
RUN apk add --no-cache gcc git libffi-dev musl-dev openssl-dev perl py-pip python3 python3-dev sshpass
RUN pip install --no-cache-dir  "ansible==$ANSIBLE_VERSION"

COPY entrypoint.sh README.md /
ENTRYPOINT [ "/entrypoint.sh" ]

LABEL os_image="$OS_IMAGE"
LABEL os_version="$OS_VERSION"
LABEL ansible_version="$ANSIBLE_VERSION"
LABEL maintainer="info@kdaweb.com"
LABEL name="Ansible test image"
LABEL description="A Docker image for Ansible v$ANSIBLE_VERSION $OS_IMAGE:$OS_VERSION"
LABEL url="https://kdaweb.com/"
LABEL vcs-ref="$VCS_REF"
LABEL build-date="$BUILD_DATE"
LABEL docker.cmd="docker run --rm -it -v "$(pwd):/workdir" wesleydean/ansible-$ANSIBLE_VERSION-tester-$OS_IMAGE:$OS_VERSION"
